// AUTO-GENERATED by tools/gen_android_aces.py - DO NOT EDIT.
// Parameter types and order are taken from Menus.cpp; ACE ids remain shared with the MFX.
package Extensions;

final class IniPlusPlusAceParams {
    static final byte STRING = 1;
    static final byte NUMBER = 2;
    static final byte INTEGER = 3;
    static final byte POSITION = 4;
    static final byte FILENAME = 5;
    static final byte FILENAME2 = 6;
    static final byte OBJECT = 7;
    private static final byte[] EMPTY = new byte[0];

    private static final byte[][] ACTION_PARAMS = new byte[][] {
        new byte[] {STRING, NUMBER},
        new byte[] {STRING, NUMBER, NUMBER},
        new byte[] {STRING, STRING},
        new byte[] {STRING, STRING},
        new byte[] {OBJECT, NUMBER, NUMBER},
        new byte[] {OBJECT},
        new byte[] {STRING, POSITION},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {STRING},
        new byte[] {STRING, NUMBER},
        new byte[] {STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, NUMBER, NUMBER},
        new byte[] {STRING, STRING, STRING},
        new byte[] {STRING, STRING, STRING},
        new byte[] {OBJECT, STRING, NUMBER, NUMBER},
        new byte[] {OBJECT, STRING},
        new byte[] {STRING, STRING, POSITION},
        new byte[] {STRING},
        new byte[] {STRING},
        new byte[] {STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, NUMBER},
        new byte[] {STRING, STRING, STRING, STRING},
        new byte[] {STRING},
        new byte[] {STRING, STRING},
        new byte[] {STRING},
        new byte[] {STRING, STRING, STRING, NUMBER},
        new byte[] {},
        new byte[] {STRING, STRING, STRING, OBJECT},
        new byte[] {STRING, STRING},
        new byte[] {},
        new byte[] {FILENAME2, STRING, STRING, STRING, NUMBER},
        new byte[] {OBJECT, STRING, STRING, STRING, NUMBER},
        new byte[] {FILENAME2, NUMBER},
        new byte[] {FILENAME2, STRING, STRING, NUMBER},
        new byte[] {OBJECT, NUMBER},
        new byte[] {OBJECT, STRING, STRING, NUMBER},
        new byte[] {FILENAME2, NUMBER},
        new byte[] {FILENAME2, NUMBER},
        new byte[] {},
        new byte[] {FILENAME2},
        new byte[] {FILENAME2, NUMBER, STRING},
        new byte[] {},
        new byte[] {STRING, NUMBER},
        new byte[] {NUMBER, NUMBER},
        new byte[] {NUMBER},
        new byte[] {STRING},
        new byte[] {NUMBER},
        new byte[] {NUMBER},
        new byte[] {NUMBER, NUMBER, NUMBER},
        new byte[] {NUMBER},
        new byte[] {NUMBER, NUMBER, NUMBER},
        new byte[] {STRING},
        new byte[] {STRING},
        new byte[] {FILENAME2, FILENAME2},
        new byte[] {FILENAME2, FILENAME2},
        new byte[] {STRING, OBJECT},
        new byte[] {STRING, STRING, STRING, NUMBER},
        new byte[] {},
        new byte[] {NUMBER},
        new byte[] {NUMBER, FILENAME2, STRING, STRING},
        new byte[] {NUMBER, FILENAME2, STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {STRING, NUMBER},
        new byte[] {NUMBER, NUMBER},
        new byte[] {STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {STRING, STRING, NUMBER, STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {OBJECT, STRING},
        new byte[] {FILENAME2, OBJECT},
        new byte[] {},
        new byte[] {},
        new byte[] {NUMBER},
        new byte[] {},
        new byte[] {NUMBER},
    };

    private static final byte[][] CONDITION_PARAMS = new byte[][] {
        new byte[] {},
        new byte[] {STRING},
        new byte[] {STRING, STRING, STRING},
        new byte[] {STRING},
        new byte[] {STRING, STRING},
        new byte[] {STRING, STRING, STRING, STRING},
        new byte[] {STRING, STRING, NUMBER},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
        new byte[] {},
    };

    private static final byte[][] EXPRESSION_PARAMS = new byte[][] {
        new byte[] {STRING, INTEGER},
        new byte[] {STRING, STRING},
        new byte[] {STRING},
        new byte[] {STRING},
        new byte[] {INTEGER},
        new byte[] {INTEGER},
        new byte[] {INTEGER},
        new byte[] {},
        new byte[] {STRING, STRING, INTEGER},
        new byte[] {STRING, STRING, STRING},
        new byte[] {STRING, STRING},
        new byte[] {STRING, STRING},
        new byte[] {INTEGER},
        new byte[] {STRING, INTEGER},
        new byte[] {STRING, INTEGER},
        new byte[] {STRING, INTEGER},
        new byte[] {},
        new byte[] {STRING},
        new byte[] {},
        new byte[] {},
        new byte[] {INTEGER},
        new byte[] {INTEGER},
        new byte[] {INTEGER},
        new byte[] {INTEGER},
        new byte[] {INTEGER, STRING},
        new byte[] {},
        new byte[] {STRING},
        new byte[] {STRING, STRING},
        new byte[] {STRING},
        new byte[] {STRING},
        new byte[] {STRING, STRING},
        new byte[] {STRING, STRING},
        new byte[] {STRING, INTEGER},
        new byte[] {STRING, INTEGER},
        new byte[] {STRING, STRING},
        new byte[] {INTEGER},
        new byte[] {},
        new byte[] {STRING, STRING, INTEGER, STRING},
        new byte[] {},
        new byte[] {},
        new byte[] {},
    };

    static byte[] forAction(int id) {
        return id >= 0 && id < ACTION_PARAMS.length ? ACTION_PARAMS[id] : EMPTY;
    }

    static byte[] forCondition(int id) {
        return id >= 0 && id < CONDITION_PARAMS.length ? CONDITION_PARAMS[id] : EMPTY;
    }

    static byte[] forExpression(int id) {
        return id >= 0 && id < EXPRESSION_PARAMS.length ? EXPRESSION_PARAMS[id] : EMPTY;
    }

    private IniPlusPlusAceParams() {}
}
